version: "3"

vars:
  PROJECT_ROOT:
    sh: echo $PWD

env:
  PROJECT_ROOT: "{{.PROJECT_ROOT}}"
  OSCAL_CLI_BIN: "{{.PROJECT_ROOT}}/OSCAL-CLI/cli-core/target/cli-core-0.3.0-oscal-cli/bin"
  CATALOGS_DIR: "{{.PROJECT_ROOT}}/src/catalogs"
  MAPPINGS_DIR: "{{.PROJECT_ROOT}}/src/mappings"
  OSCAL_XML_SCHEMA_DIR: "{{.PROJECT_ROOT}}/OSCAL/xml/schema"

tasks:
  sub-init:
    cmds:
      - git submodule update --init --recursive
  build-oscal-cli:
    dir: OSCAL-CLI
    cmds:
      - mvn clean install
  oscal-cli:
    cmds:
      - $OSCAL_CLI_BIN/oscal-cli {{.CLI_ARGS}}
  convert-catalogs:
    cmds:
      - task oscal-cli -- catalog convert --overwrite --to json "$CATALOGS_DIR/xml/cis-controls-v8_OSCAL-1.0.xml" "$CATALOGS_DIR/json/cis-controls-v8_OSCAL-1.0.json"
      - task oscal-cli -- catalog convert --overwrite --to yaml "$CATALOGS_DIR/xml/cis-controls-v8_OSCAL-1.0.xml" "$CATALOGS_DIR/yaml/cis-controls-v8_OSCAL-1.0.yaml"
  convert-mappings:
    cmds:
      - task oscal-cli -- mapping-collection convert --overwrite --to json "$MAPPINGS_DIR/xml/CCM_CISControlsv8_Mapping.xml" "$MAPPINGS_DIR/json/CCM_CISControlsv8_Mapping.json"
      - task oscal-cli -- mapping-collection convert --overwrite --to yaml "$MAPPINGS_DIR/xml/CCM_CISControlsv8_Mapping.xml" "$MAPPINGS_DIR/yaml/CCM_CISControlsv8_Mapping.yaml"
      - task oscal-cli -- mapping-collection convert --overwrite --to json "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.xml" "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.json"
      - task oscal-cli -- mapping-collection convert --overwrite --to yaml "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.xml" "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.yaml"
  validate-catalogs:
    cmds:
      - xmllint --noout --schema "$OSCAL_XML_SCHEMA_DIR/oscal_catalog_schema.xsd" "$CATALOGS_DIR/xml/cis-controls-v8_OSCAL-1.0.xml"
#      - task oscal-cli -- catalog validate --as xml "$CATALOGS_DIR/xml/cis-controls-v8_OSCAL-1.0.xml"
      - task oscal-cli -- catalog validate --as json "$CATALOGS_DIR/json/cis-controls-v8_OSCAL-1.0.json"
      - task oscal-cli -- catalog validate --as yaml "$CATALOGS_DIR/yaml/cis-controls-v8_OSCAL-1.0.yaml"
  validate-mappings:
    cmds:
      - xmllint --noout --schema "$OSCAL_XML_SCHEMA_DIR/oscal_mapping_schema.xsd" "$MAPPINGS_DIR/xml/CCM_CISControlsv8_Mapping.xml"
      - xmllint --noout --schema "$OSCAL_XML_SCHEMA_DIR/oscal_mapping_schema.xsd" "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.xml"
#      - task oscal-cli -- mapping-collection validate --as xml "$MAPPINGS_DIR/xml/CCM_CISControlsv8_Mapping.xml"
#      - task oscal-cli -- mapping-collection validate --as xml "$MAPPINGS_DIR/SP_800_53MOD_CISControlsv8_Mapping.xml"
